name: flame_game
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  audioplayers: ^1.0.1
  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  firebase_database: ^9.0.20
  flame: ^1.2.1
  flame_audio: ^1.3.0
  flame_tiled: ^1.5.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  get_it: ^7.2.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  uuid: ^3.0.6

dev_dependencies:
  blackfoot_flutter_lint: ^1.0.6

  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/audio/loops/
    - assets/audio/sfx/
    - assets/images/
    - assets/tiles/
    - .env
