// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDInmMXZHWyWx9y1_YYVzHqoWMYzVfARWI',
    appId: '1:808769087237:web:9c1bd929e0ab0d1bc7f96c',
    messagingSenderId: '808769087237',
    projectId: 'melvyn-game-plus-plus',
    authDomain: 'melvyn-game-plus-plus.firebaseapp.com',
    storageBucket: 'melvyn-game-plus-plus.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-BinpBtwQyIeIqpu2Km42hxwONbUc0ok',
    appId: '1:808769087237:android:0cb024085f2a9c76c7f96c',
    messagingSenderId: '808769087237',
    projectId: 'melvyn-game-plus-plus',
    storageBucket: 'melvyn-game-plus-plus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ-F3c5bDa02sNuOd-wm53oBq7t1Ck7FQ',
    appId: '1:808769087237:ios:4fa810d362b676e2c7f96c',
    messagingSenderId: '808769087237',
    projectId: 'melvyn-game-plus-plus',
    storageBucket: 'melvyn-game-plus-plus.appspot.com',
    iosClientId: '808769087237-i2llktj7r6ko11lr7o3e5fu8lm46hf4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flameGame',
  );
}
