name: build
on: [pull_request]
env:
  ## Sets environment variable
  FLUTTER_ENV: prod
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: echo "FLUTTER_ENV=${{env.FLUTTER_ENV}}" > .env
      - run: flutter analyze

  build-android:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: echo "FLUTTER_ENV=${{env.FLUTTER_ENV}}" > .env
      - run: flutter build apk

  build-ios:
    needs: analyze
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          architecture: x64
      - run: echo "FLUTTER_ENV=${{env.FLUTTER_ENV}}" > .env
      - run: flutter build ios --release --no-codesign
